import { Component, OnInit, AfterViewInit, OnDestroy } from '@angular/core';
import { Router } from '@angular/router';
import { Html5Qrcode, Html5QrcodeScannerState } from 'html5-qrcode';
import { ScannerService } from '../../services/scanner.service';
import { ReceivingService } from '../../services/receiving.service';

interface POItem {
  id: number;
  poNumber: string;
  supplierName: string;
  description: string;
  boxNumber: string;
  serialNumber: string;
  quantity: number;
  poItemId: number | null;
}

@Component({
  selector: 'app-rscan',
  standalone: false,
  templateUrl: './rscan.component.html',
  styleUrl: './rscan.component.css'
})
export class RscanComponent implements OnInit, AfterViewInit, OnDestroy {
  scannerEnabled = true;
  scanResult: string | null = null;
  scannedPO: POItem | null = null;
  scannedQrCode: string | null = null;
  showReceipt = false;
  isLoading = false;
  errorMessage: string | null = null;

  private html5Qr?: Html5Qrcode;
  private readonly SCANNER_ELEMENT_ID = 'scanner-video';

  constructor(
    private router: Router,
    private scannerService: ScannerService,
    private receivingService: ReceivingService
  ) {}

  ngOnInit(): void {
    this.scannerEnabled = true;
  }

  // Camera must start AFTER Angular has actually painted the
  // <div id="scanner-video"> into the DOM — ngOnInit runs too early and
  // html5-qrcode's constructor throws "Element not found" if called there.
  ngAfterViewInit(): void {
    this.startCamera();
  }

  ngOnDestroy(): void {
    this.scannerEnabled = false;
    this.stopCamera();
  }

  private startCamera(): void {
    this.html5Qr = new Html5Qrcode(this.SCANNER_ELEMENT_ID);
    Html5Qrcode.getCameras()
      .then((cameras) => {
        if (!cameras || !cameras.length) {
          this.errorMessage = 'No camera found on this device';
          return;
        }
        this.html5Qr!.start(
          { facingMode: 'environment' },
          { fps: 10, qrbox: 250 },
          (decodedText) => this.onScanSuccess(decodedText),
          () => { /* per-frame "no QR found yet" - ignore, not an error */ }
        ).catch((err) => this.onScanError(err));
      })
      .catch((err) => this.onScanError(err));
  }

  private stopCamera(): void {
    if (this.html5Qr && this.html5Qr.getState() === Html5QrcodeScannerState.SCANNING) {
      this.html5Qr.stop().catch(() => {});
    }
  }

  // Real QR codes generated by po-qr.component.ts are plain WMS QR strings
  // (e.g. "WHQR-..."), not JSON — sent straight to the backend to validate.
  onScanSuccess(qrCode: string): void {
    if (!this.scannerEnabled) return;

    this.scannerEnabled = false;
    this.stopCamera();
    this.isLoading = true;
    this.errorMessage = null;
    this.scanResult = qrCode;
    this.scannedQrCode = qrCode;

    this.scannerService.scan(qrCode).subscribe({
      next: (res) => {
        this.scannedPO = {
          id: 1,
          poNumber: res.data.poNumber,
          supplierName: res.data.supplierName,
          description: res.data.itemName || '',
          boxNumber: res.data.itemCode || '',
          serialNumber: `${res.data.poNumber}-${res.data.itemCode || ''}`,
          quantity: res.data.orderedQty || 0,
          poItemId: res.data.poItemId ?? null
        };
        this.showReceipt = true;
        this.isLoading = false;
      },
      error: (err) => {
        this.errorMessage = err?.error?.message || 'Invalid QR code or scan failed';
        this.isLoading = false;
        setTimeout(() => {
          this.scannerEnabled = true;
          this.startCamera();
        }, 2000);
      }
    });
  }

  onScanError(error: any): void {
    console.error('Scan error:', error);
    this.errorMessage = 'Failed to access camera. Please check permissions.';
  }

  // "Accept" — creates the real Receiving Verification record (Step 4),
  // defaulting received qty to the ordered qty; the Receive screen lets
  // staff correct it before Confirm.
  acceptPO(): void {
    if (!this.scannedPO || !this.scannedQrCode || this.scannedPO.poItemId == null) return;

    this.isLoading = true;
    this.receivingService.create({
      qrCode: this.scannedQrCode,
      items: [{ poItemId: this.scannedPO.poItemId, receivedQty: this.scannedPO.quantity }]
    }).subscribe({
      next: (res) => {
        this.isLoading = false;
        // res.data.receivingNumber is WMS's own receiving reference (e.g. RCV-WH-...),
        // not a GRN — no GRN exists yet at this point, it's only minted later by
        // VISIPACK once QC Incoming Approval actually accepts the material.
        alert(`✅ PO ${this.scannedPO?.poNumber} received — receiving ref ${res.data.receivingNumber}. Continue in the Receive screen to upload documents and confirm.`);
        this.router.navigate(['/recieve']);
      },
      error: (err) => {
        this.isLoading = false;
        alert(err?.error?.message || 'Failed to create receiving record');
      }
    });
  }

  // Read-only re-confirmation of what was scanned — doesn't write anything.
  verifyPO(): void {
    if (!this.scannedPO) return;
    alert(`🔍 PO ${this.scannedPO.poNumber} / ${this.scannedPO.description} — details match what VISIPACK has on record.`);
  }

  resetScanner(): void {
    this.scanResult = null;
    this.scannedPO = null;
    this.scannedQrCode = null;
    this.showReceipt = false;
    this.errorMessage = null;
    this.isLoading = false;
    this.scannerEnabled = true;
    this.startCamera();
  }

  goBack(): void {
    this.router.navigate(['/main-menu']);
  }

  rescan(): void {
    this.resetScanner();
  }
}